name: Deploy

on:
    workflow_run:
        workflows:
            - Testing
        types:
            - completed

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: akhileshns/heroku-deploy@v3.8.9
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: 'reaql-frontend'
                  heroku_email: 'dan.exxx1st@gmail.com'
